# Tests this action success by the application already being installed on the repository

name: Test Success - installed action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use action 
        id: use_action
        uses: ./
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Use token to read details
        uses: actions/github-script@v2
        with:
          github-token: ${{ steps.use_action.outputs.token }}
          script: |
            const repo = await github.getOctokit(process.env.TOKEN).repos.get(context.repo);
            console.log(JSON.stringify(repo, null, 2));
